/**
 * Health metrics for /panel/salud (paso-09). Real traffic only
 * (is_synthetic = false, mode = live); the drift section uses the synthetic
 * weeks generated by scripts/simulate-traffic.ts and says so.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { LINES, type Line } from "@/lib/catalog/lines";

export const DRIFT_ALERT_TVD = 0.2;

const percentile = (xs: number[], p: number) => {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil(p * s.length) - 1)];
};

export interface HealthReport {
  turns: number;
  conversations: number;
  totalCostUsd: number;
  costPerConversationUsd: number | null;
  latencyP50Ms: number | null;
  latencyP95Ms: number | null;
  ttftP50Ms: number | null;
  ttftP95Ms: number | null;
  errorRate: number | null;
  toolUseRate: number | null;
  toolCounts: Record<string, number>;
  byModel: Record<string, number>;
  evals: {
    version: string;
    createdAt: string;
    casePassRate: number | null;
    noInventedPrices: number | null;
    costUsd: number | null;
  }[];
  drift: {
    baseline: Record<Line, number>;
    current: Record<Line, number>;
    baselineN: number;
    currentN: number;
    tvd: number | null;
    alert: boolean;
  };
}

/** Total variation distance between two distributions over the same categories (0 = identical, 1 = disjoint). */
export function totalVariation(a: Record<string, number>, b: Record<string, number>): number {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  let sum = 0;
  for (const k of keys) sum += Math.abs((a[k] ?? 0) - (b[k] ?? 0));
  return sum / 2;
}

function shares(lines: (string | null)[]): Record<Line, number> {
  const known = lines.filter((l): l is Line => !!l && (LINES as readonly string[]).includes(l));
  return Object.fromEntries(
    LINES.map((l) => [l, known.length ? known.filter((x) => x === l).length / known.length : 0]),
  ) as Record<Line, number>;
}

export async function getHealthReport(db: SupabaseClient): Promise<HealthReport> {
  const [{ data: rows }, { data: runs }, { data: synth }] = await Promise.all([
    db
      .from("interactions")
      .select("conversation_id, model, cost_usd, latency_ms, ttft_ms, tools_used, error")
      .eq("is_synthetic", false)
      .eq("mode", "live")
      .order("created_at", { ascending: false })
      .limit(5000),
    db
      .from("eval_runs")
      .select("version, created_at, summary, cost_usd, mode")
      .eq("mode", "live")
      .order("created_at", { ascending: true }),
    db.from("conversations").select("session_id, line").eq("is_synthetic", true),
  ]);

  const interactions = rows ?? [];
  const costByConv = new Map<string, number>();
  for (const r of interactions) {
    if (r.conversation_id)
      costByConv.set(r.conversation_id, (costByConv.get(r.conversation_id) ?? 0) + Number(r.cost_usd));
  }
  const toolCounts: Record<string, number> = {};
  const byModel: Record<string, number> = {};
  for (const r of interactions) {
    for (const t of (r.tools_used as string[]) ?? []) toolCounts[t] = (toolCounts[t] ?? 0) + 1;
    byModel[r.model] = (byModel[r.model] ?? 0) + 1;
  }
  const lat = interactions.map((r) => r.latency_ms).filter((x): x is number => typeof x === "number");
  const ttft = interactions.map((r) => r.ttft_ms).filter((x): x is number => typeof x === "number");
  const n = interactions.length;

  const baselineLines = (synth ?? []).filter((c) => c.session_id === "synthetic-baseline").map((c) => c.line);
  const currentLines = (synth ?? []).filter((c) => c.session_id === "synthetic-drift").map((c) => c.line);
  const baseline = shares(baselineLines);
  const current = shares(currentLines);
  const tvd = baselineLines.length && currentLines.length ? totalVariation(baseline, current) : null;

  return {
    turns: n,
    conversations: costByConv.size,
    totalCostUsd: interactions.reduce((a, r) => a + Number(r.cost_usd), 0),
    costPerConversationUsd: costByConv.size
      ? [...costByConv.values()].reduce((a, b) => a + b, 0) / costByConv.size
      : null,
    latencyP50Ms: percentile(lat, 0.5),
    latencyP95Ms: percentile(lat, 0.95),
    ttftP50Ms: percentile(ttft, 0.5),
    ttftP95Ms: percentile(ttft, 0.95),
    errorRate: n ? interactions.filter((r) => r.error).length / n : null,
    toolUseRate: n
      ? interactions.filter((r) => ((r.tools_used as string[]) ?? []).length > 0).length / n
      : null,
    toolCounts,
    byModel,
    evals: (runs ?? []).map((r) => ({
      version: r.version,
      createdAt: r.created_at,
      casePassRate: (r.summary as { casePassRate?: number })?.casePassRate ?? null,
      noInventedPrices:
        (r.summary as { checks?: { no_off_catalog_prices?: { rate: number } } })?.checks
          ?.no_off_catalog_prices?.rate ?? null,
      costUsd: r.cost_usd === null ? null : Number(r.cost_usd),
    })),
    drift: {
      baseline,
      current,
      baselineN: baselineLines.length,
      currentN: currentLines.length,
      tvd,
      alert: tvd !== null && tvd > DRIFT_ALERT_TVD,
    },
  };
}
