import type { EmailOtpType } from "@supabase/supabase-js";
import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * Magic-link landing. Supports both flows:
 * - ?code=...                 (PKCE, default email template)
 * - ?token_hash=...&type=...  (token hash, e.g. links generated by the admin API)
 */
export async function GET(request: NextRequest) {
  const url = new URL(request.url);
  const next = url.searchParams.get("next")?.startsWith("/panel") ? url.searchParams.get("next")! : "/panel";
  const supabase = await createClient();

  const code = url.searchParams.get("code");
  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type") as EmailOtpType | null;

  const { error } = code
    ? await supabase.auth.exchangeCodeForSession(code)
    : tokenHash && type
      ? await supabase.auth.verifyOtp({ type, token_hash: tokenHash })
      : { error: new Error("missing token") };

  return NextResponse.redirect(new URL(error ? "/panel/login?error=1" : next, url.origin));
}
