/**
 * Ingest the catalog into Supabase for retrieval.
 *
 *   pnpm ingest            -> chunk, embed (if VOYAGE_API_KEY) and upsert changed documents
 *   pnpm ingest --force    -> re-ingest everything
 *
 * Full-text search always works (the `fts` column is generated by Postgres).
 * Embeddings are optional: without VOYAGE_API_KEY, chunks are stored with a
 * null embedding and retrieval falls back to FTS only.
 */
import { config } from "dotenv";
import { createHash } from "node:crypto";
import { loadPolicies, loadServices } from "../lib/catalog/load";
import { chunkMarkdown } from "../lib/rag/chunking";
import { embed, embeddingsAvailable, EMBEDDING_MODEL } from "../lib/rag/embeddings";
import { createAdminClient } from "../lib/supabase/admin";

config({ path: ".env.local", quiet: true });

interface SourceDoc {
  sourcePath: string;
  title: string;
  kind: "service" | "policy";
  serviceId: string | null;
  content: string;
}

async function main() {
  const force = process.argv.includes("--force");
  const db = createAdminClient();
  const docs: SourceDoc[] = [
    ...loadServices().map((s) => ({
      sourcePath: s.sourcePath,
      title: s.name,
      kind: "service" as const,
      serviceId: s.id,
      content: s.content,
    })),
    ...loadPolicies().map((p) => ({
      sourcePath: p.sourcePath,
      title: p.title,
      kind: "policy" as const,
      serviceId: null,
      content: p.content,
    })),
  ];
  const withEmbeddings = embeddingsAvailable();
  console.log(
    `${docs.length} documents · embeddings: ${withEmbeddings ? EMBEDDING_MODEL : "OFF (FTS only)"}`,
  );

  let ingested = 0;
  let chunkCount = 0;
  for (const doc of docs) {
    const checksum = createHash("sha256").update(doc.content).digest("hex");
    const { data: existing } = await db
      .from("documents")
      .select("id, checksum")
      .eq("source_path", doc.sourcePath)
      .maybeSingle();
    if (existing && existing.checksum === checksum && !force) continue;

    // Embed first: if it fails, the document is not marked as ingested (checksum).
    const chunks = chunkMarkdown(doc.title, doc.content);
    const embeddings = withEmbeddings
      ? await embed(
          chunks.map((c) => c.content),
          "document",
          { retryOn429: 6 },
        )
      : null;

    const { data: saved, error } = await db
      .from("documents")
      .upsert(
        {
          source_path: doc.sourcePath,
          title: doc.title,
          kind: doc.kind,
          service_id: doc.serviceId,
          content: doc.content,
          checksum,
          updated_at: new Date().toISOString(),
        },
        { onConflict: "source_path" },
      )
      .select("id")
      .single();
    if (error) throw error;

    await db.from("chunks").delete().eq("document_id", saved.id);
    const { error: chunkError } = await db.from("chunks").insert(
      chunks.map((c, i) => ({
        document_id: saved.id,
        chunk_index: c.index,
        heading: c.heading,
        content: c.content,
        embedding: embeddings ? JSON.stringify(embeddings[i]) : null,
      })),
    );
    if (chunkError) throw chunkError;
    ingested++;
    chunkCount += chunks.length;
    console.log(`  ✓ ${doc.sourcePath} (${chunks.length} chunks)`);
  }
  console.log(`Done: ${ingested} documents updated, ${chunkCount} chunks written.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
