/**
 * Record the hotel demo for AI_MODE=mock (the talk's plan B).
 *
 *   pnpm record-mocks
 *
 * Plays the scripted hotel conversation against the REAL model, with a
 * middleware that captures every raw model stream (one per agent step), and
 * saves them to data/mocks/hotel.json. Tools run in offline mode (local
 * catalog search, create_request does not write to the database), exactly as
 * they will during the mock replay, so the recording and the replay match.
 */
import { anthropic } from "@ai-sdk/anthropic";
import { streamText, wrapLanguageModel, type LanguageModelMiddleware, type ModelMessage } from "ai";
import { config } from "dotenv";
import { writeFileSync } from "node:fs";
import { buildCopilotRequest, COPILOT_MODEL, PROMPT_VERSION } from "../lib/ai/copilot";

config({ path: ".env.local", quiet: true });

export const HOTEL_TURNS = [
  "Tengo un hotel boutique de 24 habitaciones en Getsemaní, el Hotel Brisas de Getsemaní. En temporada alta (diciembre y enero) se forman filas de hasta 40 minutos en el check-in entre las 2 y las 5 de la tarde. Tenemos 2 recepcionistas. Llegan unos 18 huéspedes por hora en el pico y cada check-in toma unos 6 minutos. Los huéspedes se quejan en las reseñas. ¿Qué me recomiendan?",
  "Sí, guárdala por favor. Soy Marcela Pérez, del Hotel Brisas de Getsemaní.",
];

const steps: { chunks: unknown[] }[] = [];

const recorder: LanguageModelMiddleware = {
  specificationVersion: "v4",
  wrapStream: async ({ doStream }) => {
    const result = await doStream();
    const chunks: unknown[] = [];
    const tap = new TransformStream({
      transform(chunk, controller) {
        chunks.push(chunk);
        controller.enqueue(chunk);
      },
      flush() {
        steps.push({ chunks });
      },
    });
    return { ...result, stream: result.stream.pipeThrough(tap) };
  },
};

const model = wrapLanguageModel({ model: anthropic(COPILOT_MODEL), middleware: recorder });
const conversationId = "00000000-0000-4000-8000-000000000001";

async function turn(messages: ModelMessage[]) {
  const result = streamText({ ...buildCopilotRequest(messages, { conversationId, mode: "mock" }), model });
  let text = "";
  for await (const part of result.stream) {
    if (part.type === "text-delta") text += part.text;
    if (part.type === "tool-call") console.log(`  → tool ${part.toolName}`);
    if (part.type === "error") throw part.error;
  }
  // All steps' messages (tool calls + tool results + text), not just the last step.
  return { text, responseMessages: await result.responseMessages, content: await result.content };
}

async function main() {
  const messages: ModelMessage[] = [{ role: "user", content: HOTEL_TURNS[0] }];
  console.log("turn 1 (hotel case)");
  const t1 = await turn(messages);
  messages.push(...t1.responseMessages);

  console.log("turn 2 (user asks to save)");
  messages.push({ role: "user", content: HOTEL_TURNS[1] });
  const t2 = await turn(messages);
  messages.push(...t2.responseMessages);
  const approvals = t2.content.filter((p) => p.type === "tool-approval-request");
  if (approvals.length === 0) throw new Error("Expected an approval request for create_request in turn 2");

  console.log("turn 3 (user approves in the UI)");
  messages.push({
    role: "tool",
    content: approvals.map((a) => ({
      type: "tool-approval-response" as const,
      approvalId: a.approvalId,
      approved: true,
    })),
  });
  await turn(messages);

  writeFileSync(
    "data/mocks/hotel.json",
    JSON.stringify(
      {
        _note:
          "Generated by scripts/record-mocks.ts. Raw model stream per agent step, replayed by lib/ai/mock-model.ts.",
        recordedAt: new Date().toISOString(),
        model: COPILOT_MODEL,
        promptVersion: PROMPT_VERSION,
        userTurns: HOTEL_TURNS,
        steps,
      },
      null,
      1,
    ) + "\n",
  );
  console.log(`saved data/mocks/hotel.json (${steps.length} model steps)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
