/**
 * Seed the database with the fictional catalog and demo MIPYMES.
 *
 *   pnpm seed          -> upsert into the remote Supabase project (.env.local)
 *   pnpm seed --sql    -> write supabase/seed.sql (for `supabase db reset` locally)
 *
 * Idempotent: services are upserted by id; demo requests (is_demo_seed = true)
 * are replaced on every run.
 */
import { config } from "dotenv";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { loadServices } from "../lib/catalog/load";
import { createAdminClient } from "../lib/supabase/admin";

config({ path: ".env.local", quiet: true });

interface DemoCompany {
  id: string;
  company: string;
  contact_name: string;
  problem: string;
  line: string;
  recommended_services: string[];
  scope: string;
  investment_range_cop: string;
  status: string;
}

const companies: DemoCompany[] = JSON.parse(
  readFileSync(path.join(process.cwd(), "data", "mipymes.json"), "utf8"),
).companies;

const services = loadServices().map((s) => ({
  id: s.id,
  name: s.name,
  line: s.line,
  summary: s.summary,
  price_min_cop: s.priceMinCop,
  price_max_cop: s.priceMaxCop,
  duration: s.duration,
  source_path: s.sourcePath,
}));

const demoRequests = companies.map((c) => ({
  company: c.company,
  contact_name: c.contact_name,
  contact_email: null,
  line: c.line,
  problem_summary: c.problem,
  recommended_services: c.recommended_services,
  scope: c.scope,
  investment_range_cop: c.investment_range_cop,
  status: c.status,
  is_demo_seed: true,
}));

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `array[${value.map(sqlLiteral).join(", ")}]::text[]`;
  return `'${String(value).replaceAll("'", "''")}'`;
}

function toInsert(table: string, rows: Record<string, unknown>[], conflict?: string): string {
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${cols.map((c) => sqlLiteral(r[c])).join(", ")})`).join(",\n");
  const onConflict = conflict
    ? `\non conflict (${conflict}) do update set ${cols
        .filter((c) => c !== conflict)
        .map((c) => `${c} = excluded.${c}`)
        .join(", ")}`
    : "";
  return `insert into public.${table} (${cols.join(", ")}) values\n${values}${onConflict};\n`;
}

async function writeSqlFile() {
  const sql = [
    "-- GENERATED by `pnpm seed --sql` from data/catalog and data/mipymes.json. Do not edit by hand.",
    "-- Fictional data for the Innova Copilot educational demo.\n",
    toInsert("services", services, "id"),
    "delete from public.requests where is_demo_seed;",
    toInsert("requests", demoRequests),
  ].join("\n");
  writeFileSync(path.join(process.cwd(), "supabase", "seed.sql"), sql);
  console.log(`supabase/seed.sql written: ${services.length} services, ${demoRequests.length} demo requests`);
}

async function seedRemote() {
  const db = createAdminClient();

  const { error: servicesError } = await db.from("services").upsert(services, { onConflict: "id" });
  if (servicesError) throw servicesError;

  const { error: deleteError } = await db.from("requests").delete().eq("is_demo_seed", true);
  if (deleteError) throw deleteError;
  const { error: requestsError } = await db.from("requests").insert(demoRequests);
  if (requestsError) throw requestsError;

  const staff = (process.env.STAFF_EMAILS ?? "").split(",").filter(Boolean);
  const { data: staffCount, error: staffError } = await db.rpc("sync_staff_allowlist", { p_emails: staff });
  if (staffError) throw staffError;

  console.log(
    `Seeded remote: ${services.length} services, ${demoRequests.length} demo requests, ${staffCount} staff emails`,
  );
}

const run = process.argv.includes("--sql") ? writeSqlFile : seedRemote;
run().catch((err) => {
  console.error(err);
  process.exit(1);
});
