-- Innova Copilot — initial schema (paso-02-arquitectura-datos)
-- Catalog + RAG storage, conversations, pre-proposals (requests), telemetry,
-- evals and rate limiting. RLS is enabled on every table: the public (anon)
-- role has NO direct access; the Next.js server uses the service role, and
-- staff (allowlisted emails) can read through RLS policies in /panel.

create extension if not exists vector with schema extensions;

create schema if not exists private;

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------
create table public.services (
  id text primary key,                       -- slug, e.g. 'simulacion-operaciones'
  name text not null,
  line text not null check (line in ('quality_assurance', 'business_innovation', 'process_design')),
  summary text not null,
  price_min_cop bigint not null check (price_min_cop >= 0),
  price_max_cop bigint not null check (price_max_cop >= price_min_cop),
  duration text not null,
  source_path text not null unique,          -- data/catalog/<file>.md
  updated_at timestamptz not null default now()
);

create table public.documents (
  id bigint generated always as identity primary key,
  source_path text not null unique,
  title text not null,
  kind text not null check (kind in ('service', 'policy')),
  service_id text references public.services (id) on delete set null,
  content text not null,
  checksum text not null,                    -- sha256 of content, to skip unchanged files on ingest
  updated_at timestamptz not null default now()
);
create index documents_service_id_idx on public.documents (service_id);

create table public.chunks (
  id bigint generated always as identity primary key,
  document_id bigint not null references public.documents (id) on delete cascade,
  chunk_index int not null,
  heading text,
  content text not null,
  embedding extensions.vector(1024),         -- voyage-3.5-lite; null when no VOYAGE_API_KEY
  fts tsvector generated always as (
    to_tsvector('spanish', coalesce(heading, '') || ' ' || content)
  ) stored,
  unique (document_id, chunk_index)
);
create index chunks_embedding_hnsw_idx on public.chunks
  using hnsw (embedding extensions.vector_cosine_ops);
create index chunks_fts_gin_idx on public.chunks using gin (fts);

-- ---------------------------------------------------------------------------
-- Conversations and pre-proposals
-- ---------------------------------------------------------------------------
create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  ip_hash text,                              -- sha256(ip + salt); never the raw IP
  prompt_version text,
  line text check (line in ('quality_assurance', 'business_innovation', 'process_design')),
  message_count int not null default 0,
  has_proposal boolean not null default false,
  is_synthetic boolean not null default false, -- traffic generated by scripts/simulate-traffic.ts
  started_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);
create index conversations_started_at_idx on public.conversations (started_at desc);

create table public.messages (
  id bigint generated always as identity primary key,
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool')),
  content jsonb not null,
  created_at timestamptz not null default now()
);
create index messages_conversation_id_idx on public.messages (conversation_id, created_at);

create table public.requests (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.conversations (id) on delete set null,
  company text not null,
  contact_name text not null,
  contact_email text,
  line text not null check (line in ('quality_assurance', 'business_innovation', 'process_design')),
  problem_summary text not null,
  recommended_services text[] not null default '{}',
  scope text not null,
  investment_range_cop text not null,
  status text not null default 'new' check (status in ('new', 'in_review', 'proposal_sent', 'closed')),
  is_demo_seed boolean not null default false, -- fictional seed data
  created_at timestamptz not null default now()
);
create index requests_conversation_id_idx on public.requests (conversation_id);
create index requests_line_status_idx on public.requests (line, status, created_at desc);

-- ---------------------------------------------------------------------------
-- Telemetry (one row per assistant turn)
-- ---------------------------------------------------------------------------
create table public.interactions (
  id bigint generated always as identity primary key,
  conversation_id uuid references public.conversations (id) on delete cascade,
  created_at timestamptz not null default now(),
  mode text not null check (mode in ('live', 'mock')),
  model text not null,
  prompt_version text not null,
  input_tokens int not null default 0,
  output_tokens int not null default 0,
  cache_read_tokens int not null default 0,
  cache_write_tokens int not null default 0,
  cost_usd numeric(12, 6) not null default 0,
  latency_ms int,                            -- full turn
  ttft_ms int,                               -- time to first token
  tools_used text[] not null default '{}',
  error text,
  is_synthetic boolean not null default false
);
create index interactions_conversation_id_idx on public.interactions (conversation_id);
create index interactions_created_at_idx on public.interactions (created_at desc);

-- ---------------------------------------------------------------------------
-- Evals
-- ---------------------------------------------------------------------------
create table public.eval_runs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  version text not null,                     -- e.g. 'paso-03-primer-llm'
  git_sha text,
  mode text not null check (mode in ('live', 'mock')),
  dataset_size int not null,
  summary jsonb not null,                    -- aggregated metrics, as written to evals/results/*.json
  cost_usd numeric(12, 6),
  notes text
);

create table public.eval_results (
  id bigint generated always as identity primary key,
  run_id uuid not null references public.eval_runs (id) on delete cascade,
  case_id text not null,
  passed boolean not null,
  checks jsonb not null,                     -- deterministic checks
  judge jsonb,                               -- LLM-as-judge scores
  output text,
  tool_calls jsonb,
  latency_ms int,
  cost_usd numeric(12, 6)
);
create index eval_results_run_id_idx on public.eval_results (run_id);

-- ---------------------------------------------------------------------------
-- Rate limiting (fixed windows) and staff allowlist
-- ---------------------------------------------------------------------------
create table public.rate_limits (
  key text not null,                         -- 'ip:<hash>', 'session:<id>', 'daily:conversations'
  window_start timestamptz not null,
  count int not null default 0,
  primary key (key, window_start)
);

create table private.staff_allowlist (
  email text primary key check (email = lower(email))
);

-- Atomically count a hit and report whether it is still within the limit.
-- Called only by the server (service role).
create or replace function public.hit_rate_limit(p_key text, p_window_seconds int, p_max int)
returns table (allowed boolean, current_count int, reset_at timestamptz)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_window timestamptz := to_timestamp(floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds);
  v_count int;
begin
  insert into public.rate_limits as rl (key, window_start, count)
  values (p_key, v_window, 1)
  on conflict (key, window_start) do update set count = rl.count + 1
  returning rl.count into v_count;

  return query select v_count <= p_max, v_count, v_window + make_interval(secs => p_window_seconds);
end;
$$;
revoke execute on function public.hit_rate_limit(text, int, int) from public, anon, authenticated;
grant execute on function public.hit_rate_limit(text, int, int) to service_role;

-- True when the logged-in user's email is on the staff allowlist.
create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from private.staff_allowlist
    where email = lower((select auth.jwt() ->> 'email'))
  );
$$;
revoke execute on function private.is_staff() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_staff() to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.services      enable row level security;
alter table public.documents     enable row level security;
alter table public.chunks        enable row level security;
alter table public.conversations enable row level security;
alter table public.messages      enable row level security;
alter table public.requests      enable row level security;
alter table public.interactions  enable row level security;
alter table public.eval_runs     enable row level security;
alter table public.eval_results  enable row level security;
alter table public.rate_limits   enable row level security;
alter table private.staff_allowlist enable row level security;

-- anon: no policies at all -> no rows. Defense in depth: also drop table grants.
revoke all on all tables in schema public from anon;

-- Staff can read everything the panel needs, and update request status.
create policy staff_read_services      on public.services      for select to authenticated using ((select private.is_staff()));
create policy staff_read_documents     on public.documents     for select to authenticated using ((select private.is_staff()));
create policy staff_read_conversations on public.conversations for select to authenticated using ((select private.is_staff()));
create policy staff_read_messages      on public.messages      for select to authenticated using ((select private.is_staff()));
create policy staff_read_requests      on public.requests      for select to authenticated using ((select private.is_staff()));
create policy staff_update_requests    on public.requests      for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
create policy staff_read_interactions  on public.interactions  for select to authenticated using ((select private.is_staff()));
create policy staff_read_eval_runs     on public.eval_runs     for select to authenticated using ((select private.is_staff()));
create policy staff_read_eval_results  on public.eval_results  for select to authenticated using ((select private.is_staff()));
-- chunks, rate_limits and staff_allowlist: server only (service role), no policies.
